export enum CvSectionTitles {
  ABOUT = 'ABOUT',
  EDUCATION = 'EDUCATION',
  COMPUTER_SKILLS = 'COMPUTER_SKILLS',
  FOREIGN_LANGUAGES = 'FOREIGN_LANGUAGES',
  EXPERIENCES = 'EXPERIENCES',
  PROJECTS = 'PROJECTS',
  CONTACT = 'CONTACT'
}
